// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/pull-request/interfaces/pull-request-repo.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	entity "github.com/SmokingElk/avito-2025-autumn-intership/internal/domain/pull-request/entity"
	interfaces "github.com/SmokingElk/avito-2025-autumn-intership/internal/domain/pull-request/interfaces"
	gomock "github.com/golang/mock/gomock"
)

// MockPullRequestRepo is a mock of PullRequestRepo interface.
type MockPullRequestRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepoMockRecorder
}

// MockPullRequestRepoMockRecorder is the mock recorder for MockPullRequestRepo.
type MockPullRequestRepoMockRecorder struct {
	mock *MockPullRequestRepo
}

// NewMockPullRequestRepo creates a new mock instance.
func NewMockPullRequestRepo(ctrl *gomock.Controller) *MockPullRequestRepo {
	mock := &MockPullRequestRepo{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepo) EXPECT() *MockPullRequestRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPullRequestRepo) Create(ctx context.Context, pr entity.PullRequest, assign interfaces.AssignHandler) (entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pr, assign)
	ret0, _ := ret[0].(entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPullRequestRepoMockRecorder) Create(ctx, pr, assign interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPullRequestRepo)(nil).Create), ctx, pr, assign)
}

// GetByReviewer mocks base method.
func (m *MockPullRequestRepo) GetByReviewer(ctx context.Context, reviewerId string, limit int) ([]entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReviewer", ctx, reviewerId, limit)
	ret0, _ := ret[0].([]entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReviewer indicates an expected call of GetByReviewer.
func (mr *MockPullRequestRepoMockRecorder) GetByReviewer(ctx, reviewerId, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReviewer", reflect.TypeOf((*MockPullRequestRepo)(nil).GetByReviewer), ctx, reviewerId, limit)
}

// Reassign mocks base method.
func (m *MockPullRequestRepo) Reassign(ctx context.Context, prId, oldReviewerId string, assign interfaces.ReassignHandler) (entity.PullRequest, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reassign", ctx, prId, oldReviewerId, assign)
	ret0, _ := ret[0].(entity.PullRequest)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Reassign indicates an expected call of Reassign.
func (mr *MockPullRequestRepoMockRecorder) Reassign(ctx, prId, oldReviewerId, assign interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reassign", reflect.TypeOf((*MockPullRequestRepo)(nil).Reassign), ctx, prId, oldReviewerId, assign)
}

// UpdateStatus mocks base method.
func (m *MockPullRequestRepo) UpdateStatus(ctx context.Context, prId string, updateStatusHandler interfaces.UpdateStatusHandler) (entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, prId, updateStatusHandler)
	ret0, _ := ret[0].(entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockPullRequestRepoMockRecorder) UpdateStatus(ctx, prId, updateStatusHandler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockPullRequestRepo)(nil).UpdateStatus), ctx, prId, updateStatusHandler)
}
