// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/team/interfaces/team-repo.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	entity "github.com/SmokingElk/avito-2025-autumn-intership/internal/domain/team/entity"
	interfaces "github.com/SmokingElk/avito-2025-autumn-intership/internal/domain/team/interfaces"
	gomock "github.com/golang/mock/gomock"
)

// MockTeamRepo is a mock of TeamRepo interface.
type MockTeamRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepoMockRecorder
}

// MockTeamRepoMockRecorder is the mock recorder for MockTeamRepo.
type MockTeamRepoMockRecorder struct {
	mock *MockTeamRepo
}

// NewMockTeamRepo creates a new mock instance.
func NewMockTeamRepo(ctrl *gomock.Controller) *MockTeamRepo {
	mock := &MockTeamRepo{ctrl: ctrl}
	mock.recorder = &MockTeamRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepo) EXPECT() *MockTeamRepoMockRecorder {
	return m.recorder
}

// GetByName mocks base method.
func (m *MockTeamRepo) GetByName(ctx context.Context, name string) (entity.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(entity.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockTeamRepoMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockTeamRepo)(nil).GetByName), ctx, name)
}

// Upsert mocks base method.
func (m *MockTeamRepo) Upsert(ctx context.Context, team entity.Team, matcher interfaces.TeamMatcher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, team, matcher)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockTeamRepoMockRecorder) Upsert(ctx, team, matcher interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockTeamRepo)(nil).Upsert), ctx, team, matcher)
}
