// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/member/interfaces/member-repo.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	entity "github.com/SmokingElk/avito-2025-autumn-intership/internal/domain/member/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockMemberRepo is a mock of MemberRepo interface.
type MockMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMemberRepoMockRecorder
}

// MockMemberRepoMockRecorder is the mock recorder for MockMemberRepo.
type MockMemberRepoMockRecorder struct {
	mock *MockMemberRepo
}

// NewMockMemberRepo creates a new mock instance.
func NewMockMemberRepo(ctrl *gomock.Controller) *MockMemberRepo {
	mock := &MockMemberRepo{ctrl: ctrl}
	mock.recorder = &MockMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberRepo) EXPECT() *MockMemberRepoMockRecorder {
	return m.recorder
}

// SetActivity mocks base method.
func (m *MockMemberRepo) SetActivity(ctx context.Context, userId string, activity entity.MemberActivity) (entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActivity", ctx, userId, activity)
	ret0, _ := ret[0].(entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetActivity indicates an expected call of SetActivity.
func (mr *MockMemberRepoMockRecorder) SetActivity(ctx, userId, activity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActivity", reflect.TypeOf((*MockMemberRepo)(nil).SetActivity), ctx, userId, activity)
}
