// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/statistics/interfaces/stats-repo.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	entity "github.com/SmokingElk/avito-2025-autumn-intership/internal/domain/statistics/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockStatsRepo is a mock of StatsRepo interface.
type MockStatsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockStatsRepoMockRecorder
}

// MockStatsRepoMockRecorder is the mock recorder for MockStatsRepo.
type MockStatsRepoMockRecorder struct {
	mock *MockStatsRepo
}

// NewMockStatsRepo creates a new mock instance.
func NewMockStatsRepo(ctrl *gomock.Controller) *MockStatsRepo {
	mock := &MockStatsRepo{ctrl: ctrl}
	mock.recorder = &MockStatsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsRepo) EXPECT() *MockStatsRepoMockRecorder {
	return m.recorder
}

// GetAssignmentsPerMember mocks base method.
func (m *MockStatsRepo) GetAssignmentsPerMember(ctx context.Context, limit, offset int) ([]entity.AssignmentsPerMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignmentsPerMember", ctx, limit, offset)
	ret0, _ := ret[0].([]entity.AssignmentsPerMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignmentsPerMember indicates an expected call of GetAssignmentsPerMember.
func (mr *MockStatsRepoMockRecorder) GetAssignmentsPerMember(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignmentsPerMember", reflect.TypeOf((*MockStatsRepo)(nil).GetAssignmentsPerMember), ctx, limit, offset)
}
